// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	ID                string `json:"_id"`
	FirstName         string `json:"first_name"`
	LastName          string `json:"last_name"`
	Description       string `json:"description"`
	BirthDate         string `json:"birth_date"`
	ComicBooksWritten string `json:"comic_books_written"`
}

type Character struct {
	ID              string `json:"_id"`
	Name            string `json:"name"`
	Description     string `json:"description"`
	ComicBookSeries string `json:"comic_book_series"`
	Superpower      string `json:"superpower"`
	DangerLevel     int    `json:"danger_level"`
}

type ComicBook struct {
	ID              string `json:"_id"`
	Name            string `json:"name"`
	Description     string `json:"description"`
	PublicationDate string `json:"publication_date"`
	Author          string `json:"author"`
}

type ComicBookStore struct {
	ID          string `json:"_id"`
	Name        string `json:"name"`
	Location    string `json:"location"`
	PostalCode  string `json:"postal_code"`
	Description string `json:"description"`
	PhoneNumber string `json:"phone_number"`
	StoreOwner  string `json:"store_owner"`
}

type CreateAuthorInput struct {
	FirstName         string `json:"first_name"`
	LastName          string `json:"last_name"`
	Description       string `json:"description"`
	BirthDate         string `json:"birth_date"`
	ComicBooksWritten string `json:"comic_books_written"`
}

type CreateCharacterInput struct {
	Name            string `json:"name"`
	Description     string `json:"description"`
	ComicBookSeries string `json:"comic_book_series"`
	Superpower      string `json:"superpower"`
	DangerLevel     int    `json:"danger_level"`
}

type CreateComicBookInput struct {
	Name            string `json:"name"`
	Description     string `json:"description"`
	PublicationDate string `json:"publication_date"`
	Author          string `json:"author"`
}

type CreateComicBookStoreInput struct {
	Name        string `json:"name"`
	Location    string `json:"location"`
	PostalCode  string `json:"postal_code"`
	Description string `json:"description"`
	PhoneNumber string `json:"phone_number"`
	StoreOwner  string `json:"store_owner"`
}

type DeleteAuthorResponse struct {
	DeletedAuthorID string `json:"deletedAuthorId"`
}

type DeleteCharacterResponse struct {
	DeletedCharacterID string `json:"deletedCharacterId"`
}

type DeleteComicBookResponse struct {
	DeletedComicBookID string `json:"deletedComicBookId"`
}

type DeleteComicBookStoreResponse struct {
	DeletedComicBookStoreID string `json:"deletedComicBookStoreId"`
}

type UpdateAuthorInput struct {
	FirstName         *string `json:"first_name"`
	LastName          *string `json:"last_name"`
	Description       *string `json:"description"`
	BirthDate         *string `json:"birth_date"`
	ComicBooksWritten *string `json:"comic_books_written"`
}

type UpdateCharacterInput struct {
	Name            *string `json:"name"`
	Description     *string `json:"description"`
	ComicBookSeries *string `json:"comic_book_series"`
	Superpower      *string `json:"superpower"`
	DangerLevel     *int    `json:"danger_level"`
}

type UpdateComicBookInput struct {
	Name            *string `json:"name"`
	Description     *string `json:"description"`
	PublicationDate *string `json:"publication_date"`
	Author          *string `json:"author"`
}

type UpdateComicBookStoreInput struct {
	Name        *string `json:"name"`
	Location    *string `json:"location"`
	PostalCode  *string `json:"postal_code"`
	Description *string `json:"description"`
	PhoneNumber *string `json:"phone_number"`
	StoreOwner  *string `json:"store_owner"`
}
